### ISSUE TITLE
磁盘空间不足

### ISSUE THREAD

**Issue by blueroutecn** [kevin-meng/HuggingfaceDownloadShare#3]
不能完成一个模型下载，有没有解决方案？

**Comment by kevin-meng** [comment]
是colab空间不足？

**Comment by blueroutecn** [comment]
是docker中的空间不足，能不能实现指定文件下载，在页面中能浏览huggingface主要内容，然后指定下载单个文件下载，避免空间不足的问题。

**Comment by sxd1140** [comment]
是`play-with-dcoker`空间不足

**Comment by kevin-meng** [comment]
已支持选择文件下载
