### ISSUE TITLE
模型权重过大占满磁盘，即使挂载了谷歌云盘，还是会有挂载机制缓存无法下载

### ISSUE THREAD

**Issue by shenhu365** [kevin-meng/HuggingfaceDownloadShare#6]
有些模型权重过大，超过**100G**(colab分配的磁盘容量)

然后我挂载了谷歌云盘**1T**内存，也将下载缓存和保存目录等等都设置在了谷歌云盘目录下

但还是因为挂载机制，会把文件临时缓存到```/root/.config/Google/DriveFS/```下，这样导致还是无法下载大型权重

有其他方法可以直接保存到谷歌云盘吗或者有别的解决办法嘛

**Comment by JieShenAI** [comment]
你没有开colab pro+，免费用户不能用Colab的高RAM。

**Comment by kevin-meng** [comment]
可以试试 AWS EC2 按时付费，把空间选大点。然后把项目克隆过运用。
AWS 有免费时长。应该可以解决你的问题。
